### ISSUE TITLE
Less of an issue, more of a question.

### ISSUE THREAD

**Issue by GavinDarkglider** [CTCaer/minerva_tc#1]
Sorry to post this here, as this is against ettiqute, but I was curious if this would be a viable replacement in core boot for the propriatary tegra_mtc.bin file? If so, how much of the code do you think would need to change in the current memory training code to support this? I only ask, because it would be nice to be able to keep everything opensource. I am not against putting in the work on this, but I really dont know the first thing about low level programming like this, so any pointers on how to port support to coreboot would be nice.

**Comment by CTCaer** [comment]
It is viable as it is for coreboot.

It only needs static ompilation to 0x81000000 and a change of the caller to use the struct.
What I want to do actually is implementing it in the kernel. So I have to change floats to ints.

I still haven't decided how to go about this.
Maybe even keep it around as a module or sth and set a specific address that keeps the ram tables.

**Comment by GavinDarkglider** [comment]
Well, with that I am happy to see that there is still some thought of linux development in the switch scene. I am excited to see what you come up with. Personally I have been trying to come up with a solution to the USB issues for months, but havnt had much luck. lol. That being said, it is a completly different problem to this, so, I will thank you for the answer you gave, and let you get back to work.
